First pass at documenting maskbits
desihub/desidatamodel pull request #139
Opened 2022-11-18 20:04 UTC by forero

First version for the maskbits documentation. It simply links to the source code on desihub where the meaning for each bit in the mask is explained.

2022-11-18 22:58 UTC, weaverba137 requested changes
Looks good so far, with some minor changes. I think it is an open question though whether we want the general public digging down into the YAML files for the individual bits.

2022-11-18 22:58 UTC, weaverba137 commented on doc/bitmasks.rst
> +Redshift fitting (Redrock) masks
I would make these sub-headings, then Sphinx will automatically create links to the subheadings.

2022-11-18 22:58 UTC, weaverba137 commented on doc/bitmasks.rst
> +ZWARN		                        `ZWARN`_
It looks like you've got TAB characters instead of spaces.  I know this is fussy, but spaces will be better supported long-term.

2023-01-31 18:24 UTC, forero commented
Hi @weaverba137.  I think I have addressed the two issues that you raised. Please let me know what you think.

2023-01-31 18:30 UTC, weaverba137 approved these changes

2023-01-31 18:30 UTC, weaverba137 commented
Thank you looks good.

2023-01-31 18:30 UTC, merged